[package]
name = "starsign"
version = "0.1.4"
authors = ["mintthemoon <mint@mintthemoon.xyz>"]
description = "Cosmos node configuration, simplified. ğŸš€ğŸªğŸŒ"
documentation = "https://github.com/mintthemoon/starsign/blob/main/README.md"
homepage = "https://mintthemoon.xyz"
repository = "https://github.com/mintthemoon/starsign"
readme = "README.md"
license = "MIT"
edition = "2021"
include = [
    "**/*.rs",
    "data/*",
    "templates/*",
    "Cargo.toml",
]

[dependencies]
askama = "0.11.1"
anyhow = { version = "1.0" }
reqwest = { version = "0.11.14", features = ["stream"] }
clap = { version = "4.1.6", features = ["derive"] }
serde = "1.0.152"
serde_json = { version = "1.0.93", features = ["preserve_order"] }
json-patch = "0.3.0"
log = "0.4.17"
env_logger = "0.10.0"
gethostname = "0.4.1"
tendermint-rpc = { version = "0.27.0", features=["http-client"] }
tokio = "1.25.0"
docker-api = "0.13.0"
futures = "0.3.27"
lazy_static = "1.4.0"
async-compression = { version = "0.3.15", features = ["futures-io", "gzip"] }
